### ISSUE TITLE
Improvement : use angular universal

### ISSUE THREAD

**Issue by pvdyck** [stefanoslig/angular-ngrx-nx-realworld-example-app#10]
If you want to compare apples with apples, you should really consider upgrading this example with angular universal.

Howto here => https://medium.com/@philip_lysenko/angular-universal-with-nrwl-nx-ca2996a7da2

First paint will be much better, download size should be too, only LoC will not improve.

**Comment by stefanoslig** [comment]
Hi @pvdyck. Thanks for your suggestion and for the reference to your article. In the upcoming weeks, I will update this repo to the latest angular/nrwl/ngrx versions and also I will add angular universal as well.
