### ISSUE TITLE
Article follow/unfollow duplicated effects

### ISSUE THREAD

**Issue by andrzejpindor** [stefanoslig/angular-ngrx-nx-realworld-example-app#241]
I noticed that  `articlesActions.favorite` and `articlesActions.unfavorite` have effects in:
* https://github.com/stefanoslig/angular-ngrx-nx-realworld-example-app/blob/main/libs/articles/data-access/src/lib/%2Bstate/article/article.effects.ts#L12
* https://github.com/stefanoslig/angular-ngrx-nx-realworld-example-app/blob/main/libs/articles/data-access/src/lib/%2Bstate/article-list/article-list.effects.ts#L52

For this reason when user follows there steps:

1. enter products list (articles-list feature store is loaded)
2. enter product page (article feature store is loaded)
3. clicks favorite button on article details page
4. both effects from both feature stores are fired, causing duplicated request for backend

Is it intended behavior? What would be the best clean solution to deal with this situation if we need to get rid off this duplicated request?

**Comment by stefanoslig** [comment]
Hi Andrzej!

Very nice observation, thank you! I think the solution is quite simple. I extracted these effects to a separate file and I provide the same effects to both routes. You can check the solution on this commit: https://github.com/stefanoslig/angular-ngrx-nx-realworld-example-app/commit/4ca27267fc477cb99e68251e62d925f4582e0a8a
