### ISSUE TITLE
Replace placeholder in email login input

### ISSUE THREAD

**Issue by mathisvester** [stefanoslig/angular-ngrx-nx-realworld-example-app#294]
The placeholder of the email input shows:  "Username". It suggests that the user can put in username. It would be better to replace it with "Email" because authentication with username is not supported.

**Comment by mathisvester** [comment]
@stefanoslig can you trigger deployment for https://conduit-af252.firebaseapp.com?

**Comment by stefanoslig** [comment]
Hi @mathisvester . It is deployed now. Could you check again?

**Comment by mathisvester** [comment]
@stefanoslig looks fine. Thank you!
