### ISSUE TITLE
Does not compile

### ISSUE THREAD

**Issue by shoff** [stefanoslig/angular-ngrx-nx-realworld-example-app#3]
`ERROR in node_modules/@types/jasmine/index.d.ts(14,18): error TS2300: Duplicate identifier 'describe'.
node_modules/@types/jasmine/index.d.ts(15,18): error TS2300: Duplicate identifier 'fdescribe'.
node_modules/@types/jasmine/index.d.ts(16,18): error TS2300: Duplicate identifier 'xdescribe'.
node_modules/@types/jasmine/index.d.ts(25,18): error TS2300: Duplicate identifier 'it'.
node_modules/@types/jasmine/index.d.ts(34,18): error TS2300: Duplicate identifier 'fit'.
node_modules/@types/jasmine/index.d.ts(35,18): error TS2300: Duplicate identifier 'xit'.
node_modules/@types/jasmine/index.d.ts(50,18): error TS2300: Duplicate identifier 'beforeEach'.
node_modules/@types/jasmine/index.d.ts(57,18): error TS2300: Duplicate identifier 'afterEach'.
node_modules/@types/jasmine/index.d.ts(65,18): error TS2300: Duplicate identifier 'beforeAll'.
node_modules/@types/jasmine/index.d.ts(73,18): error TS2300: Duplicate identifier 'afterAll'.
node_modules/@types/jasmine/index.d.ts(79,18): error TS2451: Cannot redeclare block-scoped variable 'expect'.
node_modules/@types/jasmine/index.d.ts(85,18): error TS2451: Cannot redeclare block-scoped variable 'expect'.
node_modules/@types/jasmine/index.d.ts(91,18): error TS2451: Cannot redeclare block-scoped variable 'expect'.
node_modules/@types/jasmine/index.d.ts(96,18): error TS2451: Cannot redeclare block-scoped variable 'expect'.
node_modules/@types/jasmine/index.d.ts(135,9): error TS2300: Duplicate identifier 'clock'.
node_modules/@types/jasmine/index.d.ts(181,15): error TS2428: All declarations of 'ArrayContaining' must have identical type parameters.
node_modules/@types/jasmine/index.d.ts(188,15): error TS2428: All declarations of 'ObjectContaining' must have identical type parameters.
node_modules/@types/jasmine/index.d.ts(219,10): error TS2300: Duplicate identifier 'CustomEqualityTester'.
node_modules/@types/jasmine/index.d.ts(228,10): error TS2300: Duplicate identifier 'CustomMatcherFactory'.
node_modules/@types/jasmine/index.d.ts(710,16): error TS2451: Cannot redeclare block-scoped variable 'DEFAULT_TIMEOUT_INTERVAL'.
node_modules/@types/jasminewd2/index.d.ts(9,18): error TS2300: Duplicate identifier 'it'.
node_modules/@types/jasminewd2/index.d.ts(10,18): error TS2300: Duplicate identifier 'fit'.
node_modules/@types/jasminewd2/index.d.ts(11,18): error TS2300: Duplicate identifier 'xit'.
node_modules/@types/jasminewd2/index.d.ts(12,18): error TS2300: Duplicate identifier 'beforeEach'.
node_modules/@types/jasminewd2/index.d.ts(13,18): error TS2300: Duplicate identifier 'afterEach'.
node_modules/@types/jasminewd2/index.d.ts(14,18): error TS2300: Duplicate identifier 'beforeAll'.
node_modules/@types/jasminewd2/index.d.ts(15,18): error TS2300: Duplicate identifier 'afterAll'.
node_modules/@types/jest/index.d.ts(22,13): error TS2300: Duplicate identifier 'beforeAll'.
node_modules/@types/jest/index.d.ts(23,13): error TS2300: Duplicate identifier 'beforeEach'.
node_modules/@types/jest/index.d.ts(24,13): error TS2300: Duplicate identifier 'afterAll'.
node_modules/@types/jest/index.d.ts(25,13): error TS2300: Duplicate identifier 'afterEach'.
node_modules/@types/jest/index.d.ts(26,13): error TS2300: Duplicate identifier 'describe'.
node_modules/@types/jest/index.d.ts(27,13): error TS2300: Duplicate identifier 'fdescribe'.
node_modules/@types/jest/index.d.ts(28,13): error TS2300: Duplicate identifier 'xdescribe'.
node_modules/@types/jest/index.d.ts(29,13): error TS2300: Duplicate identifier 'it'.
node_modules/@types/jest/index.d.ts(30,13): error TS2300: Duplicate identifier 'fit'.
node_modules/@types/jest/index.d.ts(31,13): error TS2300: Duplicate identifier 'xit'.
node_modules/@types/jest/index.d.ts(35,15): error TS2451: Cannot redeclare block-scoped variable 'expect'.
node_modules/@types/jest/index.d.ts(933,9): error TS2451: Cannot redeclare block-scoped variable 'DEFAULT_TIMEOUT_INTERVAL'.
node_modules/@types/jest/index.d.ts(934,14): error TS2300: Duplicate identifier 'clock'.
node_modules/@types/jest/index.d.ts(937,46): error TS2314: Generic type 'ArrayContaining<T>' requires 1 type argument(s).
node_modules/@types/jest/index.d.ts(938,45): error TS2314: Generic type 'ObjectContaining<T>' requires 1 type argument(s).
node_modules/@types/jest/index.d.ts(964,15): error TS2428: All declarations of 'ArrayContaining' must have identical type parameters.
node_modules/@types/jest/index.d.ts(970,15): error TS2428: All declarations of 'ObjectContaining' must have identical type parameters.
node_modules/@types/jest/index.d.ts(1078,9): error TS2374: Duplicate string index signature.
node_modules/@types/jest/index.d.ts(1081,10): error TS2300: Duplicate identifier 'CustomMatcherFactory'.
node_modules/@types/jest/index.d.ts(1089,10): error TS2300: Duplicate identifier 'CustomEqualityTester'.
node_modules/@types/jest/index.d.ts(1098,9): error TS2687: All declarations of 'message' must have identical modifiers.
node_modules/@types/jest/index.d.ts(1098,9): error TS2717: Subsequent property declarations must have the same type.  Property 'message' must be of type 'string', but here has type 'string | (() => string)'.
node_modules/@types/jest/index.d.ts(1103,9): error TS2375: Duplicate number index signature.`

**Comment by stefanoslig** [comment]
build should be ok now.

P.S I'm currently working on unit testing
