### ISSUE TITLE
No articles found on first app load

### ISSUE THREAD

**Issue by Dodje** [stefanoslig/angular-ngrx-nx-realworld-example-app#302]
No console or network error, except that there is no request in network tab. Might be some lifecycle bug
https://angular-ngrx-nx.netlify.app/home

![image](https://github.com/stefanoslig/angular-ngrx-nx-realworld-example-app/assets/25726086/5812a042-fac8-40d1-b207-370ad150ec55)

**Comment by stefanoslig** [comment]
Hi @Dodje . Thank you for reporting the issue. That broke after a recent migration to NgRx Signals Store. It should be fixed now
