### ISSUE TITLE
Articles fetching event is being accumulated

### ISSUE THREAD

**Issue by Dodje** [stefanoslig/angular-ngrx-nx-realworld-example-app#312]
STR:

1. Load Home page. Do not log in.
2. Click on the favorite button of any article on the main page
    -> `loadArticles` is being invoked on redirect to login page
3. Click logo to go back to home page
    -> `loadArticles` is being invoked twice

Repeat steps 1 and 2.

**Comment by stefanoslig** [comment]
Hey @Dodje . Very nice observation! It's because of how the rxMethod subscribes to the $listConfig signal.

```ts
this.articlesListStore.loadArticles(this.$listConfig);
```

I'm going to fix this tomorrow!

**Comment by Dodje** [comment]
> Hey @Dodje . Very nice observation! It's because of how the rxMethod subscribes to the $listConfig signal.
> 
> ```ts
> this.articlesListStore.loadArticles(this.$listConfig);
> ```
> 
> I'm going to fix this tomorrow!

Thanks :) I've tried to dive into it, but I'm not very familiar with rxjs, so my attempts were in vain haha

**Comment by stefanoslig** [comment]
it should be fine now. Thanks for reporting it!
