### ISSUE TITLE
tsconfig.app.json

### ISSUE THREAD

**Issue by alexus85** [stefanoslig/angular-ngrx-nx-realworld-example-app#41]
I'm just wondering, why do you include all these libs in your **tsconfig.app.json**?

```
  "include": [
    "**/*.d.ts",
    "../../libs/home/src/index.ts",
    "../../libs/editor/src/index.ts",
    "../../libs/settings/src/index.ts",
    "../../libs/article/src/index.ts",
    "../../libs/profile/src/index.ts"
  ],
```

Is the reason behind this, just to have all these modules included in the main bundle? 
Or you just want the ready as soon as the apps is loaded? 

Cause I think more elegant solution would be setting the **preloadingStrategy** to:

```
RouterModule.forRoot( routes, {
   preloadingStrategy: PreloadAllModules
})
```
what do you think?

**Comment by stefanoslig** [comment]
The include property is removed
