### ISSUE TITLE
Question about the architecture

### ISSUE THREAD

**Issue by lujakob** [stefanoslig/angular-ngrx-nx-realworld-example-app#5]
Hi Stefano...
I am debugging your app for learning purposes. Thumbs up, I think it's very well coded. 
I have a question regarding your architecture choices: 

Why are you creating an ArticleGuardService to only dispatch this.facade.loadArticle - why are you not just calling loadArticle and loadComments in ngOnInit of the article.component ?

Thanks!

**Comment by stefanoslig** [comment]
Hi @lujakob ,
Thank you!
It's a long time since I worked in this file. You could just call loadArticle and loadComments in ngOnInit as well without problem. It's a more pessimistic approach where you prevent the user to navigate if the article is deleted for example.
