### ISSUE TITLE
Uncaught NullInjectorError: NullInjectorError: No provider for InjectionToken API_URL

### ISSUE THREAD

**Issue by naujoks-stefan** [stefanoslig/angular-ngrx-nx-realworld-example-app#95]
Hallo,

I downloaded your code an tried to run. The app is compiled well without any exception. When I open my browser with localhost:4200 app is not loaded. Opened my browser dev tools and see the exception: 
Uncaught NullInjectorError: NullInjectorError: No provider for InjectionToken API_URL!

How can I fix?
Best Stefan

**Comment by stefanoslig** [comment]
Hi @naujoks-stefan . Thanks for reporting this issue! It's due to a PR that was merged yesterday. 

I fixed it. If you `git pull`, it should be fine now
